-- 1. Table Schema
CREATE TABLE IF NOT EXISTS public.restaurants (
  id TEXT PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  categories TEXT[] NOT NULL DEFAULT '{}',
  is_city_wide BOOLEAN NOT NULL DEFAULT false,
  branches TEXT[] NOT NULL DEFAULT '{}',
  dining_mode TEXT NOT NULL CHECK (dining_mode IN ('both', 'delivery_only', 'dine_in_only')),
  time_slots TEXT[] NOT NULL DEFAULT '{}',
  closing_time_ar TEXT NOT NULL,
  is_open_late BOOLEAN NOT NULL DEFAULT false,
  is_24_hours BOOLEAN NOT NULL DEFAULT false,
  avg_prep_minutes INTEGER NOT NULL DEFAULT 20,
  tier TEXT NOT NULL CHECK (tier IN ('staple', 'trend')),
  price_tier TEXT NOT NULL CHECK (price_tier IN ('$', '$$', '$$$')),
  signature_dish_ar TEXT NOT NULL,
  signature_dish_en TEXT NOT NULL,
  vibe_tags_ar TEXT[] NOT NULL DEFAULT '{}',
  vibe_tags_en TEXT[] NOT NULL DEFAULT '{}',
  rating NUMERIC(2,1) NOT NULL DEFAULT 4.5,
  platforms JSONB NOT NULL DEFAULT '{"hungerstation": false, "jahez": false, "keeta": false}'::jsonb,
  links JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. RLS & Permissions
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'restaurants' AND policyname = 'Allow public read access on restaurants'
  ) THEN
    CREATE POLICY "Allow public read access on restaurants" ON public.restaurants FOR SELECT USING (true);
  END IF;
END $$;

-- 3. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_restaurants_categories ON public.restaurants USING GIN (categories);
CREATE INDEX IF NOT EXISTS idx_restaurants_branches ON public.restaurants USING GIN (branches);
CREATE INDEX IF NOT EXISTS idx_restaurants_is_city_wide ON public.restaurants (is_city_wide);

-- 4. SEED DATA (PART 1: Burgers, Shawarma, Broast, Kabsa, Pizza, Late Night, Grills)
INSERT INTO public.restaurants (
  id, name_ar, name_en, categories, is_city_wide, branches, dining_mode,
  time_slots, closing_time_ar, is_open_late, is_24_hours, avg_prep_minutes,
  tier, price_tier, signature_dish_ar, signature_dish_en, vibe_tags_ar, vibe_tags_en,
  rating, platforms, links
) VALUES
  -- Burgers
  ('century_burger', 'سنشري برجر', 'Century Burger', ARRAY['burger'], false, ARRAY['al_mohammadiyyah', 'al_rawdah', 'al_shati', 'abhur_al_shamaliyah', 'al_faiha'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 20, 'staple', '$$', 'سنشري برجر مع صوص CB 🍔', 'Century Burger with CB Sauce 🍔', ARRAY['قديم ومعروف', 'خبز طازج', 'سهرات'], ARRAY['Jeddah Classic', 'Fresh Buns', 'Late Night'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Century+Burger+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Century+Burger", "jahezSearch": "https://jahez.net/search?q=Century+Burger", "keetaSearch": "https://keeta.com/search?q=Century+Burger"}'),
  ('california_burger', 'كاليفورنيا برجر', 'The California Burger', ARRAY['burger'], false, ARRAY['al_khalidiyyah', 'al_mohammadiyyah', 'al_marwah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 20, 'staple', '$$', 'برجر 2x2 مع صوص كالي 🍔', '2x2 Burger with Cali Sauce 🍔', ARRAY['كلاسيك', 'لحم طازج', 'دبل جبنة'], ARRAY['Classic', 'Fresh Beef', 'Double Cheese'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=The+California+Burger+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=The+California+Burger", "jahezSearch": "https://jahez.net/search?q=The+California+Burger", "keetaSearch": "https://keeta.com/search?q=The+California+Burger"}'),
  ('section_b', 'سكشن-بي', 'Section-B', ARRAY['burger'], false, ARRAY['al_shati', 'abhur_al_shamaliyah', 'al_faisaliyyah', 'al_murjan'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 20, 'trend', '$$$', 'برجر B الكلاسيكي 🍔', 'Classic B Burger 🍔', ARRAY['ترند', 'لحم أنغوس', 'جلسات شباب'], ARRAY['Trendy', 'Angus Beef', 'Youth Hangout'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Section-B+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Section-B", "jahezSearch": "https://jahez.net/search?q=Section-B", "keetaSearch": "https://keeta.com/search?q=Section-B"}'),
  ('crave', 'كريف', 'CRAVE', ARRAY['burger'], false, ARRAY['al_andalus', 'al_basateen'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 20, 'trend', '$$', 'برايم تشاركول برجر 🍔', 'Prime Charcoal Burger 🍔', ARRAY['ترند', 'فحم', 'صوصات خاصة'], ARRAY['Trendy', 'Charcoal Grilled', 'House Sauces'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=CRAVE+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=CRAVE", "jahezSearch": "https://jahez.net/search?q=CRAVE", "keetaSearch": "https://keeta.com/search?q=CRAVE"}'),
  ('smash_me', 'سماش مي', 'Smash Me', ARRAY['burger'], false, ARRAY['al_naeem'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 18, 'trend', '$', 'سماش مي ستايل برجر 🍔', 'Smash Me Style Burger 🍔', ARRAY['سماش', 'سعره حلو', 'آخر الليل'], ARRAY['Smash Style', 'Good Value', 'Late Night'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Smash+Me+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Smash+Me", "jahezSearch": "https://jahez.net/search?q=Smash+Me", "keetaSearch": "https://keeta.com/search?q=Smash+Me"}'),
  ('chefs_burger', 'شيفز برجر', 'Chef''s Burger', ARRAY['burger'], false, ARRAY['al_zahra', 'al_mohammadiyyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:45 ص', true, false, 22, 'trend', '$$', 'شيفز دبل برجر 🍔', 'Chef''s Double Burger 🍔', ARRAY['لحم فاخر', 'مدخن', 'جلسات شباب'], ARRAY['Premium Beef', 'Smoked Meats', 'Youth Hangout'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Chef''s+Burger+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Chef''s+Burger", "jahezSearch": "https://jahez.net/search?q=Chef''s+Burger", "keetaSearch": "https://keeta.com/search?q=Chef''s+Burger"}'),
  ('wbj', 'دبليو بي جي', 'WBJ', ARRAY['burger'], false, ARRAY['al_zahra', 'abhur_al_janoubiyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 18, 'trend', '$$', 'دبل سماش برجر 🍔', 'Double Smash Burger 🍔', ARRAY['سماش', 'سريع', 'سهرات'], ARRAY['Smash Style', 'Quick Bite', 'Late Crowd'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=WBJ+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=WBJ", "jahezSearch": "https://jahez.net/search?q=WBJ", "keetaSearch": "https://keeta.com/search?q=WBJ"}'),
  ('burger_boutique', 'برجر بوتيك', 'Burger Boutique', ARRAY['burger'], false, ARRAY['al_rawdah'], 'both', ARRAY['dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 22, 'trend', '$$$', 'برجر بوتيك الكلاسيكي 🍔', 'Burger Boutique Classic 🍔', ARRAY['قورميه', 'لحم فاخر', 'جلسات'], ARRAY['Gourmet', 'Premium Beef', 'Dine-In'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Burger+Boutique+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Burger+Boutique", "jahezSearch": "https://jahez.net/search?q=Burger+Boutique", "keetaSearch": "https://keeta.com/search?q=Burger+Boutique"}'),
  ('dank', 'دانك ساندوتش', 'Dank Sandwich', ARRAY['burger', 'sandwiches'], false, ARRAY['al_zahra', 'al_rawdah', 'al_shati', 'abhur_al_shamaliyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:30 ص', true, false, 18, 'trend', '$$', 'ساندوتش ستيك لحم دانك 🥩', 'Dank Steak Sandwich 🥩', ARRAY['ترند', 'خبز طازج', 'سريع'], ARRAY['Trendy', 'Fresh Bread', 'Quick Bite'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Dank+Sandwich+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Dank", "jahezSearch": "https://jahez.net/search?q=Dank", "keetaSearch": "https://keeta.com/search?q=Dank"}'),

  -- Shawarma
  ('shawarmer', 'شاورمر', 'Shawarmer', ARRAY['shawarma'], true, ARRAY[]::text[], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 15, 'staple', '$', 'عربي شاورمر بالدجاج 🌯', 'Arabo Chicken Shawarma 🌯', ARRAY['معروف', 'ثوم زيادة', 'سريع'], ARRAY['Popular Staple', 'Extra Garlic', 'Quick Bite'], 4.1, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shawarmer+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shawarmer", "jahezSearch": "https://jahez.net/search?q=Shawarmer", "keetaSearch": "https://keeta.com/search?q=Shawarmer"}'),
  ('shawarma_shakir_aljazeera', 'شاورما شاكر الجزيرة', 'Shawarma Shakir Aljazeera', ARRAY['shawarma'], false, ARRAY['al_faisaliyyah', 'al_zahra'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 5:00 ص', true, false, 15, 'staple', '$', 'شاورما لحم خلطة شاكر 🌯', 'Shakir Mixed Meat Shawarma 🌯', ARRAY['قديم جدة', 'لحم', 'خلطة خاصة'], ARRAY['Jeddah Legend', 'Meat Shawarma', 'Signature Mix'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shawarma+Shakir+Aljazeera+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shawarma+Shakir+Aljazeera", "jahezSearch": "https://jahez.net/search?q=Shawarma+Shakir+Aljazeera", "keetaSearch": "https://keeta.com/search?q=Shawarma+Shakir+Aljazeera"}'),
  ('shawarma_allosh', 'شاورما علوش', 'Shawarma Allosh', ARRAY['shawarma'], false, ARRAY['al_naeem', 'al_safa'], 'both', ARRAY['dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 15, 'staple', '$', 'شاورما دجاج عربي 🌯', 'Arabic Chicken Shawarma 🌯', ARRAY['ثوم زيادة', 'شامي', 'سهرات'], ARRAY['Extra Garlic', 'Levant Style', 'Late Crowd'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shawarma+Allosh+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shawarma+Allosh", "jahezSearch": "https://jahez.net/search?q=Shawarma+Allosh", "keetaSearch": "https://keeta.com/search?q=Shawarma+Allosh"}'),
  ('shawarma_habteen', 'شاورما حبتين', 'Shawarma Habteen', ARRAY['shawarma'], false, ARRAY['al_shati', 'al_rawdah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 6:00 ص', true, false, 16, 'trend', '$', 'حبتين دجاج على الطريقة الشامية 🌯', 'Habteen Double Chicken Shawarma 🌯', ARRAY['حبتين', 'شامي', 'آخر الليل'], ARRAY['Double Wrap', 'Levant Style', 'Very Late'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shawarma+Habteen+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shawarma+Habteen", "jahezSearch": "https://jahez.net/search?q=Shawarma+Habteen", "keetaSearch": "https://keeta.com/search?q=Shawarma+Habteen"}'),
  ('ayedh_shawarma', 'شاورما عايض', 'Ayedh Shawarma', ARRAY['shawarma'], false, ARRAY['al_salamah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 15, 'trend', '$', 'شاورما دجاج عايض 🌯', 'Ayedh Chicken Shawarma 🌯', ARRAY['ترند', 'ثوم', 'سريع'], ARRAY['Trendy', 'Garlicky', 'Quick Bite'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Ayedh+Shawarma+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Ayedh+Shawarma", "jahezSearch": "https://jahez.net/search?q=Ayedh+Shawarma", "keetaSearch": "https://keeta.com/search?q=Ayedh+Shawarma"}'),
  ('shawarma_abu_elezz', 'شاورما أبو العز', 'Shawarma Abu Elezz', ARRAY['shawarma'], false, ARRAY['al_faiha', 'al_rehab'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:30 ص', true, false, 18, 'trend', '$', 'شاورما عربي جبنة حارة 🌯', 'Spicy Cheesy Arabic Shawarma 🌯', ARRAY['صوصات', 'جبنة', 'آخر الليل'], ARRAY['Saucy', 'Cheesy', 'Late Night'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shawarma+Abu+Elezz+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shawarma+Abu+Elezz", "jahezSearch": "https://jahez.net/search?q=Shawarma+Abu+Elezz", "keetaSearch": "https://keeta.com/search?q=Shawarma+Abu+Elezz"}'),
  ('shawarma_rubik', 'شاورما روبيك', 'Shawarma Rubik', ARRAY['shawarma'], false, ARRAY['al_rehab'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 15, 'trend', '$', 'عربي روبيك دجاج 🌯', 'Rubik Arabic Chicken Shawarma 🌯', ARRAY['مفلوكة', 'ثوم', 'سريع'], ARRAY['Maflouqa Style', 'Garlicky', 'Quick Bite'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shawarma+Rubik+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shawarma+Rubik", "jahezSearch": "https://jahez.net/search?q=Shawarma+Rubik", "keetaSearch": "https://keeta.com/search?q=Shawarma+Rubik"}'),
  ('ziyada_toum', 'زيادة ثوم', 'Ziyada Toum', ARRAY['shawarma'], false, ARRAY['al_zahra'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 18, 'trend', '$', 'شاورما دجاج ثوم زيادة 🌯', 'Extra-Garlic Chicken Shawarma 🌯', ARRAY['ثوم زيادة', 'لبناني', 'جلسات شباب'], ARRAY['Extra Garlic', 'Lebanese Style', 'Youth Hangout'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Ziyada+Toum+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Ziyada+Toum", "jahezSearch": "https://jahez.net/search?q=Ziyada+Toum", "keetaSearch": "https://keeta.com/search?q=Ziyada+Toum"}'),
  ('shawerma_alrimal', 'شاورما الرمال', 'Shawerma Alrimal', ARRAY['shawarma'], false, ARRAY['al_andalus'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 15, 'staple', '$', 'شاورما دجاج مع الثوم 🌯', 'Chicken Shawarma with Garlic 🌯', ARRAY['قديم ومعروف', 'ثوم', 'سريع'], ARRAY['Old-School', 'Garlicky', 'Quick Bite'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shawerma+Alrimal+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shawerma+Alrimal", "jahezSearch": "https://jahez.net/search?q=Shawerma+Alrimal", "keetaSearch": "https://keeta.com/search?q=Shawerma+Alrimal"}'),

  -- Broast
  ('albaik', 'البيك', 'ALBAIK', ARRAY['broast', 'burger', 'seafood'], true, ARRAY[]::text[], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 15, 'staple', '$', 'وجبة دجاج مسحب حراق 🍗', 'Spicy Chicken Nuggets Meal 🍗', ARRAY['أسطورة جدة', 'ثوم', 'سريع'], ARRAY['Jeddah Icon', 'Garlic Sauce', 'Quick Bite'], 4.8, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=ALBAIK+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=ALBAIK", "jahezSearch": "https://jahez.net/search?q=ALBAIK", "keetaSearch": "https://keeta.com/search?q=ALBAIK"}'),
  ('al_tazaj', 'الطازج', 'Al Tazaj', ARRAY['broast', 'saudi_kabsa', 'grills'], true, ARRAY[]::text[], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 20, 'staple', '$', 'وجبة بروست الطازج 🍗', 'Al Tazaj Broast Meal 🍗', ARRAY['دجاج طازج', 'رز', 'عائلي'], ARRAY['Fresh Chicken', 'Rice Meals', 'Family Friendly'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Al+Tazaj+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Al+Tazaj", "jahezSearch": "https://jahez.net/search?q=Al+Tazaj", "keetaSearch": "https://keeta.com/search?q=Al+Tazaj"}'),
  ('chicken_mubeen', 'دجاج مبين', 'Chicken Mubeen', ARRAY['broast'], true, ARRAY[]::text[], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 18, 'staple', '$', 'بروست حراق 🍗', 'Spicy Broasted Chicken 🍗', ARRAY['حراق', 'ثوم', 'سعره حلو'], ARRAY['Spicy', 'Garlic Sauce', 'Good Value'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Chicken+Mubeen+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Chicken+Mubeen", "jahezSearch": "https://jahez.net/search?q=Chicken+Mubeen", "keetaSearch": "https://keeta.com/search?q=Chicken+Mubeen"}'),
  ('rami_broast', 'بروست رامي', 'Rami Broast', ARRAY['broast'], true, ARRAY[]::text[], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 18, 'staple', '$', 'بروست دجاج حراق 🍗', 'Spicy Broasted Chicken 🍗', ARRAY['قديم ومعروف', 'حراق', 'سريع'], ARRAY['Local Staple', 'Spicy', 'Quick Bite'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Rami+Broast+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Rami+Broast", "jahezSearch": "https://jahez.net/search?q=Rami+Broast", "keetaSearch": "https://keeta.com/search?q=Rami+Broast"}'),
  ('crisper', 'كرسبر', 'Crisper', ARRAY['broast'], false, ARRAY['al_zahra', 'abhur_al_shamaliyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 5:00 ص', true, false, 18, 'trend', '$$', 'بروست كرسبر الحراق 🍗', 'Crisper Spicy Broast 🍗', ARRAY['قرمشة', 'حراق', 'آخر الليل'], ARRAY['Extra Crispy', 'Spicy', 'Very Late'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Crisper+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Crisper", "jahezSearch": "https://jahez.net/search?q=Crisper", "keetaSearch": "https://keeta.com/search?q=Crisper"}'),

  -- Saudi Kabsa / Mandi
  ('al_romansiah', 'الرومانسية', 'Al Romansiah', ARRAY['saudi_kabsa'], false, ARRAY['al_bawadi', 'al_safa'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 25, 'staple', '$$', 'رز سعودي مع لحم حنيذ 🍚', 'Saudi Rice with Haneedh Lamb 🍚', ARRAY['رز سعودي', 'لحم بلدي', 'عائلي'], ARRAY['Saudi Rice', 'Local Lamb', 'Family Friendly'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Al+Romansiah+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Al+Romansiah", "jahezSearch": "https://jahez.net/search?q=Al+Romansiah", "keetaSearch": "https://keeta.com/search?q=Al+Romansiah"}'),
  ('al_saddah', 'السدة', 'Al Saddah', ARRAY['saudi_kabsa'], false, ARRAY['al_rawdah', 'al_safa'], 'both', ARRAY['lunch', 'dinner'], 'يقفل 1:00 ص', false, false, 25, 'staple', '$$', 'مندي لحم السدة 🍚', 'Al Saddah Lamb Mandi 🍚', ARRAY['لحم بلدي', 'رز شعبي', 'عزائم'], ARRAY['Local Lamb', 'Traditional Rice', 'Group Feast'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Al+Saddah+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Al+Saddah", "jahezSearch": "https://jahez.net/search?q=Al+Saddah", "keetaSearch": "https://keeta.com/search?q=Al+Saddah"}'),
  ('raydan', 'ريدان', 'Raydan', ARRAY['saudi_kabsa'], true, ARRAY[]::text[], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 1:30 ص', true, false, 25, 'staple', '$$', 'مندي لحم ريدان 🍚', 'Raydan Lamb Mandi 🍚', ARRAY['قديم ومعروف', 'مندي', 'عائلي'], ARRAY['Longtime Staple', 'Mandi', 'Family Friendly'], 4.0, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Raydan+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Raydan", "jahezSearch": "https://jahez.net/search?q=Raydan", "keetaSearch": "https://keeta.com/search?q=Raydan"}'),
  ('mandi_world', 'مندي ورلد', 'Mandi World', ARRAY['saudi_kabsa'], false, ARRAY['al_rawdah', 'al_safa'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 25, 'staple', '$$', 'مندي لحم بلدي 🍚', 'Local Lamb Mandi 🍚', ARRAY['لحم بلدي', 'مندي', 'عزائم'], ARRAY['Local Lamb', 'Mandi', 'Group Feast'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Mandi+World+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Mandi+World", "jahezSearch": "https://jahez.net/search?q=Mandi+World", "keetaSearch": "https://keeta.com/search?q=Mandi+World"}'),
  ('matam_baladi', 'مطاعم بلدي', 'Baladi Restaurant', ARRAY['saudi_kabsa'], false, ARRAY['al_safa', 'al_bawadi', 'al_marwah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 1:30 ص', true, false, 25, 'staple', '$$', 'مندي تيس بلدي مع رز بشاور 🍚', 'Local Goat Mandi with Peshawari Rice 🍚', ARRAY['لحم بلدي', 'مندي حجازي', 'عزائم'], ARRAY['Local Meat', 'Hejazi Mandi', 'Group Feast'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Baladi+Restaurant+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Baladi", "jahezSearch": "https://jahez.net/search?q=Baladi", "keetaSearch": "https://keeta.com/search?q=Baladi"}'),

  -- Pizza
  ('maestro_pizza', 'مايسترو بيتزا', 'Maestro Pizza', ARRAY['pizza'], true, ARRAY[]::text[], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 20, 'staple', '$', 'بيتزا بيري بيري 🍕', 'Peri-Peri Pizza 🍕', ARRAY['سعره حلو', 'خيارات كثيرة', 'سريع'], ARRAY['Good Value', 'Lots of Choices', 'Quick Bite'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Maestro+Pizza+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Maestro+Pizza", "jahezSearch": "https://jahez.net/search?q=Maestro+Pizza", "keetaSearch": "https://keeta.com/search?q=Maestro+Pizza"}'),
  ('vera_pizza', 'ڤيرا', 'Vera Pizza', ARRAY['pizza'], false, ARRAY['al_zahra'], 'both', ARRAY['lunch', 'dinner'], 'يقفل 1:00 ص', false, false, 22, 'trend', '$$', 'بيتزا مارغريتا نابولية 🍕', 'Neapolitan Margherita 🍕', ARRAY['نابولي', 'عجينة خفيفة', 'جلسات'], ARRAY['Neapolitan', 'Light Dough', 'Dine-In'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Vera+Pizza+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Vera+Pizza", "jahezSearch": "https://jahez.net/search?q=Vera+Pizza", "keetaSearch": "https://keeta.com/search?q=Vera+Pizza"}'),
  ('blanca_pizzeria', 'بلانكا بيتزيريا', 'BLANCA PIZZERIA', ARRAY['pizza'], false, ARRAY['al_khalidiyyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:30 ص', true, false, 25, 'trend', '$$$', 'بيتزا ترافل 🍕', 'Truffle Pizza 🍕', ARRAY['ترند', 'ترافل', 'جلسات'], ARRAY['Trendy', 'Truffle', 'Dine-In'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=BLANCA+PIZZERIA+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=BLANCA+PIZZERIA", "jahezSearch": "https://jahez.net/search?q=BLANCA+PIZZERIA", "keetaSearch": "https://keeta.com/search?q=BLANCA+PIZZERIA"}'),
  ('il_postino_pizzeria', 'إل بوستينو بيتزيريا', 'il Postino Pizzeria', ARRAY['pizza', 'italian'], false, ARRAY['al_khalidiyyah', 'al_murjan'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 25, 'trend', '$$', 'بيتزا ديافولا 🍕', 'Diavola Pizza 🍕', ARRAY['نابولي', 'عجينة خفيفة', 'عائلي'], ARRAY['Neapolitan', 'Light Dough', 'Family Friendly'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=il+Postino+Pizzeria+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=il+Postino+Pizzeria", "jahezSearch": "https://jahez.net/search?q=il+Postino+Pizzeria", "keetaSearch": "https://keeta.com/search?q=il+Postino+Pizzeria"}'),
  ('napoli_blu', 'نابولي بلو', 'NAPOLI BLU', ARRAY['pizza'], false, ARRAY['al_rawdah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 25, 'trend', '$$', 'بيتزا مارغريتا نابولية 🍕', 'Neapolitan Margherita 🍕', ARRAY['ترند', 'نابولي', 'آخر الليل'], ARRAY['Trendy', 'Neapolitan', 'Late Night'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=NAPOLI+BLU+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=NAPOLI+BLU", "jahezSearch": "https://jahez.net/search?q=NAPOLI+BLU", "keetaSearch": "https://keeta.com/search?q=NAPOLI+BLU"}'),

  -- Late Night
  ('chan', 'شان', 'CHAN', ARRAY['late_night', 'asian'], false, ARRAY['al_zahra'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 20, 'trend', '$$', 'رامن كوري حار 🍜', 'Spicy Korean Ramen 🍜', ARRAY['أجواء حماس', 'جلسات شباب', 'سهرات جدة'], ARRAY['High Energy', 'Group Hangout', 'Jeddah Nights'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=CHAN+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=CHAN", "jahezSearch": "https://jahez.net/search?q=CHAN", "keetaSearch": "https://keeta.com/search?q=CHAN"}'),
  ('nawa_patio', 'نوى باتيو', 'Nawa Patio', ARRAY['late_night'], false, ARRAY['al_khalidiyyah'], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 22, 'trend', '$$$', 'بيتزا رمان وجرجير 🍕', 'Pomegranate & Arugula Pizza 🍕', ARRAY['لاونج رايق', 'سهرات شباب', 'جو فخم'], ARRAY['Relaxed Lounge', 'Late-Night Groups', 'Upscale'], 4.6, '{"hungerstation": false, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Nawa+Patio+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Nawa+Patio", "jahezSearch": "https://jahez.net/search?q=Nawa+Patio", "keetaSearch": "https://keeta.com/search?q=Nawa+Patio"}'),
  ('ghazal', 'غزل', 'Ghazal Restaurant', ARRAY['late_night', 'grills'], false, ARRAY['al_rawdah'], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 22, 'staple', '$$$', 'مشاوي مشكل غزل 🍢', 'Ghazal Mixed Grill 🍢', ARRAY['جلسات طربية', 'أجواء ليلية', 'قعدة طويلة'], ARRAY['Lounge Vibe', 'Night Vibes', 'Long Hangout'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Ghazal+Restaurant+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Ghazal+Restaurant", "jahezSearch": "https://jahez.net/search?q=Ghazal+Restaurant", "keetaSearch": "https://keeta.com/search?q=Ghazal+Restaurant"}'),
  ('aiglon_lounge', 'إيجلون لاونج', 'Aiglon Lounge', ARRAY['late_night'], false, ARRAY['al_rawdah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 22, 'trend', '$$$', 'ريب آي ستيك مشوي 🥩', 'Grilled Ribeye Steak 🥩', ARRAY['لايف ميوزك', 'سهرات شباب', 'جو فخم'], ARRAY['Live Music', 'Late-Night Groups', 'Upscale'], 4.4, '{"hungerstation": false, "jahez": false, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Aiglon+Lounge+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Aiglon+Lounge", "jahezSearch": "https://jahez.net/search?q=Aiglon+Lounge", "keetaSearch": "https://keeta.com/search?q=Aiglon+Lounge"}'),

  -- Grills
  ('saruja_restaurants', 'ساروجة', 'Saruja Restaurants', ARRAY['grills', 'shawarma'], false, ARRAY['al_naeem', 'al_zahra'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 20, 'staple', '$$', 'صحن مشاوي مشكل مع حمص 🍢', 'Mixed Grill Platter with Hummus 🍢', ARRAY['لحم طازج', 'مشاوي شامية', 'جلسات عائلية'], ARRAY['Fresh Meat', 'Levantine Grills', 'Family Seating'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Saruja+Restaurants+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Saruja+Restaurants", "jahezSearch": "https://jahez.net/search?q=Saruja+Restaurants", "keetaSearch": "https://keeta.com/search?q=Saruja+Restaurants"}'),
  ('shami', 'شامي', 'Shami', ARRAY['grills', 'shawarma'], false, ARRAY['al_hamra', 'al_rawdah'], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 5:30 ص', true, false, 20, 'staple', '$$', 'مشاوي شامي المشكلة 🍢', 'Shami Mixed Grill 🍢', ARRAY['شامي أصيل', 'فحم ونكهة', 'عائلي'], ARRAY['Classic Levantine', 'Charcoal Flavor', 'Family Friendly'], 4.0, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shami+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shami", "jahezSearch": "https://jahez.net/search?q=Shami", "keetaSearch": "https://keeta.com/search?q=Shami"}'),
  ('khayal', 'خيال', 'Khayal Restaurant', ARRAY['grills', 'shawarma'], false, ARRAY['al_zahra', 'abhur_al_janoubiyah'], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 22, 'staple', '$$', 'صحن مشاوي خيال بالأمتار 🍢', 'Khayal Meter Grill Platter 🍢', ARRAY['مشاوي تركية', 'عزايم', 'عائلي'], ARRAY['Turkish Grills', 'Group Feasts', 'Family Friendly'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Khayal+Restaurant+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Khayal+Restaurant", "jahezSearch": "https://jahez.net/search?q=Khayal+Restaurant", "keetaSearch": "https://keeta.com/search?q=Khayal+Restaurant"}'),
  ('al_bait_al_halabi', 'البيت الحلبي', 'Al Bait Al Halabi', ARRAY['grills'], false, ARRAY['al_salamah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 1:30 ص', true, false, 22, 'staple', '$$', 'كباب حلبي بالكرز 🍒', 'Aleppine Cherry Kebab 🍒', ARRAY['حلبي أصيل', 'مشاوي فحم', 'جلسات عائلية'], ARRAY['Aleppine Classic', 'Charcoal Grills', 'Family Seating'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Al+Bait+Al+Halabi+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Al+Bait+Al+Halabi", "jahezSearch": "https://jahez.net/search?q=Al+Bait+Al+Halabi", "keetaSearch": "https://keeta.com/search?q=Al+Bait+Al+Halabi"}')
ON CONFLICT (id) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  is_city_wide = EXCLUDED.is_city_wide,
  branches = EXCLUDED.branches,
  dining_mode = EXCLUDED.dining_mode,
  time_slots = EXCLUDED.time_slots,
  closing_time_ar = EXCLUDED.closing_time_ar,
  is_open_late = EXCLUDED.is_open_late,
  is_24_hours = EXCLUDED.is_24_hours,
  avg_prep_minutes = EXCLUDED.avg_prep_minutes,
  tier = EXCLUDED.tier,
  price_tier = EXCLUDED.price_tier,
  signature_dish_ar = EXCLUDED.signature_dish_ar,
  signature_dish_en = EXCLUDED.signature_dish_en,
  vibe_tags_ar = EXCLUDED.vibe_tags_ar,
  vibe_tags_en = EXCLUDED.vibe_tags_en,
  rating = EXCLUDED.rating,
  platforms = EXCLUDED.platforms,
  links = EXCLUDED.links;

-- 5. SEED DATA (PART 2: Italian, Asian, Healthy, Indian, Mexican, Sandwiches, Fatayer, Street Folk, Breakfast, Dessert, Seafood)
INSERT INTO public.restaurants (
  id, name_ar, name_en, categories, is_city_wide, branches, dining_mode,
  time_slots, closing_time_ar, is_open_late, is_24_hours, avg_prep_minutes,
  tier, price_tier, signature_dish_ar, signature_dish_en, vibe_tags_ar, vibe_tags_en,
  rating, platforms, links
) VALUES
  -- Italian
  ('il_posto', 'إل بوستو', 'Il Posto', ARRAY['italian', 'pizza'], false, ARRAY['al_rawdah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 1:30 ص', true, false, 22, 'trend', '$$$', 'باستا ترافل بالبارميزان 🍝', 'Truffle Parmesan Pasta 🍝', ARRAY['إيطالي فاخر', 'باستا طازجة', 'أجواء رايقة'], ARRAY['Fine Italian', 'Fresh Pasta', 'Cozy Vibe'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Il+Posto+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Il+Posto", "jahezSearch": "https://jahez.net/search?q=Il+Posto", "keetaSearch": "https://keeta.com/search?q=Il+Posto"}'),
  ('piatto', 'بياتو', 'Piatto', ARRAY['italian', 'pizza'], false, ARRAY['al_zahra', 'al_mohammadiyyah', 'al_faiha'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 20, 'staple', '$$', 'فيتوتشيني ألفريدو بالدجاج 🍝', 'Chicken Fettuccine Alfredo 🍝', ARRAY['عائلي', 'باستا وبيتزا', 'جلسات مريحة'], ARRAY['Family Friendly', 'Pasta & Pizza', 'Comfortable Seating'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Piatto+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Piatto", "jahezSearch": "https://jahez.net/search?q=Piatto", "keetaSearch": "https://keeta.com/search?q=Piatto"}'),
  ('eataly', 'إيتالي', 'Eataly', ARRAY['italian', 'pizza'], false, ARRAY['al_andalus'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 1:00 ص', false, false, 22, 'trend', '$$$', 'بيتزا مارغريتا نابوليتانا 🍕', 'Neapolitan Margherita Pizza 🍕', ARRAY['إيطالي رايق', 'قهوة وحلى', 'جلسة أنيقة'], ARRAY['Relaxed Italian', 'Coffee & Dessert', 'Elegant Seating'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Eataly+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Eataly", "jahezSearch": "https://jahez.net/search?q=Eataly", "keetaSearch": "https://keeta.com/search?q=Eataly"}'),

  -- Asian
  ('benihana', 'بينيهانا', 'Benihana', ARRAY['asian'], false, ARRAY['al_mohammadiyyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 25, 'staple', '$$$', 'تيبانياكي ستيك وروبيان 🔥', 'Steak & Shrimp Teppanyaki 🔥', ARRAY['عرض طبخ', 'عزايم', 'تجربة ممتعة'], ARRAY['Live Cooking', 'Group Feasts', 'Fun Experience'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Benihana+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Benihana", "jahezSearch": "https://jahez.net/search?q=Benihana", "keetaSearch": "https://keeta.com/search?q=Benihana"}'),
  ('pf_changs', 'بي إف تشانغز', 'P.F. Chang''s', ARRAY['asian'], false, ARRAY['al_andalus'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 25, 'staple', '$$$', 'ديناميت شرمب 🍤', 'Dynamite Shrimp 🍤', ARRAY['مشهور ومضمون', 'عائلي', 'مشاركة أطباق'], ARRAY['Reliable Favorite', 'Family Friendly', 'Sharing Plates'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=PF+Changs+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=PF+Changs", "jahezSearch": "https://jahez.net/search?q=PF+Changs", "keetaSearch": "https://keeta.com/search?q=PF+Changs"}'),
  ('wakame', 'وكامي', 'Wakame', ARRAY['asian'], false, ARRAY['al_rawdah', 'al_zahra', 'abhur_al_shamaliyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:30 ص', true, false, 25, 'trend', '$$$', 'كريسبي شرمب ماكي 🍣', 'Crispy Shrimp Maki 🍣', ARRAY['سوشي فاخر', 'أجواء رايقة', 'موعد مميز'], ARRAY['Premium Sushi', 'Relaxed Vibe', 'Date Spot'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Wakame+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Wakame", "jahezSearch": "https://jahez.net/search?q=Wakame", "keetaSearch": "https://keeta.com/search?q=Wakame"}'),

  -- Healthy
  ('boga_super_foods', 'بوقا سوبر فودس', 'BOGA Super Foods', ARRAY['healthy'], true, ARRAY[]::text[], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], '24 ساعة', true, true, 15, 'staple', '$$', 'ساندويتش دجاج بيستو مع سلطة 🥗', 'Chicken Pesto Sandwich with Salad 🥗', ARRAY['خفيف ونظيف', 'خيارات صحية', 'وجبة سريعة'], ARRAY['Light & Clean', 'Healthy Choices', 'Quick Meal'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=BOGA+Super+Foods+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=BOGA+Super+Foods", "jahezSearch": "https://jahez.net/search?q=BOGA+Super+Foods", "keetaSearch": "https://keeta.com/search?q=BOGA+Super+Foods"}'),
  ('sinless', 'سينلس', 'Sinless', ARRAY['healthy'], false, ARRAY['al_rawdah', 'al_zahra'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 11:30 م', false, false, 20, 'trend', '$$', 'سلطة بارميزان كيل 🥗', 'Parmesan Kale Salad 🥗', ARRAY['صحي ولذيذ', 'خيارات نباتية', 'قهوة رايقة'], ARRAY['Healthy & Tasty', 'Plant-Friendly', 'Relaxed Coffee'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Sinless+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Sinless", "jahezSearch": "https://jahez.net/search?q=Sinless", "keetaSearch": "https://keeta.com/search?q=Sinless"}'),
  ('be_sanus', 'بي سانوس', 'Be Sanus', ARRAY['healthy'], false, ARRAY['al_mohammadiyyah', 'al_rawdah'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 1:00 ص', false, false, 20, 'trend', '$$', 'باول دجاج بروتين مع رز 🥗', 'Chicken Protein Rice Bowl 🥗', ARRAY['بروتين عالي', 'خفيف ومشبع', 'بعد النادي'], ARRAY['High Protein', 'Light & Filling', 'Post-Workout'], 4.8, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Be+Sanus+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Be+Sanus", "jahezSearch": "https://jahez.net/search?q=Be+Sanus", "keetaSearch": "https://keeta.com/search?q=Be+Sanus"}'),

  -- Indian
  ('baba_khan', 'بابا خان', 'Baba Khan', ARRAY['indian'], false, ARRAY['al_zahra'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 25, 'staple', '$$', 'بتر تشيكن مع نان بالثوم 🍛', 'Butter Chicken with Garlic Naan 🍛', ARRAY['هندي مضمون', 'عزايم', 'نكهة قوية'], ARRAY['Reliable Indian', 'Group Feasts', 'Bold Flavor'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Baba+Khan+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Baba+Khan", "jahezSearch": "https://jahez.net/search?q=Baba+Khan", "keetaSearch": "https://keeta.com/search?q=Baba+Khan"}'),
  ('shezan', 'شيزان', 'Shezan', ARRAY['indian'], false, ARRAY['al_shati', 'al_rawdah'], 'both', ARRAY['lunch', 'dinner'], 'يقفل 12:45 ص', false, false, 25, 'staple', '$$', 'برياني دجاج مع بتر تشيكن 🍚', 'Chicken Biryani with Butter Chicken 🍚', ARRAY['قديم ومضمون', 'هندي كلاسيك', 'عائلي'], ARRAY['Old-School Favorite', 'Classic Indian', 'Family Friendly'], 4.1, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shezan+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shezan", "jahezSearch": "https://jahez.net/search?q=Shezan", "keetaSearch": "https://keeta.com/search?q=Shezan"}'),
  ('zaikaki', 'زيكاكي', 'Zaikaki Indian Cuisine', ARRAY['indian'], false, ARRAY['al_zahra'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 1:30 ص', true, false, 25, 'trend', '$$', 'مورغ تيكا مع نان بالثوم 🍗', 'Murg Tikka with Garlic Naan 🍗', ARRAY['هندي فاخر', 'بهارات موزونة', 'عشا مرتب'], ARRAY['Premium Indian', 'Balanced Spices', 'Proper Dinner'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Zaikaki+Indian+Cuisine+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Zaikaki", "jahezSearch": "https://jahez.net/search?q=Zaikaki", "keetaSearch": "https://keeta.com/search?q=Zaikaki"}'),
  ('makan_indian', 'مكان', 'Makan Indian Restaurant', ARRAY['indian'], false, ARRAY['al_khalidiyyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 1:30 ص', true, false, 25, 'trend', '$$$', 'برياني موزة لحم 🍖', 'Lamb Shank Biryani 🍖', ARRAY['هندي مودرن', 'عزايم', 'جلسة فخمة'], ARRAY['Modern Indian', 'Group Feasts', 'Upscale Seating'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Makan+Indian+Restaurant+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Makan+Indian+Restaurant", "jahezSearch": "https://jahez.net/search?q=Makan+Indian+Restaurant", "keetaSearch": "https://keeta.com/search?q=Makan+Indian+Restaurant"}'),
  ('copper_chandni', 'كوبر شندني', 'Copper Chandni', ARRAY['indian'], false, ARRAY['al_rawdah', 'al_zahra'], 'both', ARRAY['lunch', 'dinner'], 'يقفل 1:00 ص', false, false, 25, 'staple', '$$$', 'تندوري دجاج مشكل 🍗', 'Mixed Tandoori Platter 🍗', ARRAY['عريق ومضمون', 'جلسات عائلية', 'بهارات أصيلة'], ARRAY['Longstanding Classic', 'Family Seating', 'Authentic Spices'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Copper+Chandni+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Copper+Chandni", "jahezSearch": "https://jahez.net/search?q=Copper+Chandni", "keetaSearch": "https://keeta.com/search?q=Copper+Chandni"}'),

  -- Mexican
  ('firegrill', 'فاير جريل', 'FireGrill', ARRAY['mexican'], false, ARRAY['al_zahra', 'al_naeem'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 18, 'staple', '$$', 'بوريتو بريسكيت مع جواكامولي 🌯', 'Brisket Burrito with Guacamole 🌯', ARRAY['فريش مكس', 'يشبع', 'اختيارات كثيرة'], ARRAY['Fresh Mex', 'Filling', 'Lots of Choices'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=FireGrill+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=FireGrill", "jahezSearch": "https://jahez.net/search?q=FireGrill", "keetaSearch": "https://keeta.com/search?q=FireGrill"}'),
  ('eds_taco', 'إدز تاكو', 'ED''S Taco', ARRAY['mexican'], false, ARRAY['al_zahra'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 20, 'trend', '$$', 'بيريا تاكو لحم مع كونسومي 🌮', 'Beef Birria Tacos with Consommé 🌮', ARRAY['بيريا مضبوط', 'سهرات شباب', 'نكهة قوية'], ARRAY['Proper Birria', 'Late-Night Groups', 'Bold Flavor'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=EDS+Taco+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=EDS+Taco", "jahezSearch": "https://jahez.net/search?q=EDS+Taco", "keetaSearch": "https://keeta.com/search?q=EDS+Taco"}'),
  ('cocina_la_cantina', 'كوسينا لا كانتينا', 'Cocina La Cantina', ARRAY['mexican'], false, ARRAY['al_zahra'], 'dine_in_only', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 1:45 ص', true, false, 22, 'trend', '$$$', 'تاكو كارني أسادا 🌮', 'Carne Asada Tacos 🌮', ARRAY['مكسيكي مرتب', 'موعد لطيف', 'أجواء حيوية'], ARRAY['Proper Mexican', 'Date Spot', 'Lively Vibe'], 4.7, '{"hungerstation": false, "jahez": false, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Cocina+La+Cantina+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Cocina+La+Cantina", "jahezSearch": "https://jahez.net/search?q=Cocina+La+Cantina", "keetaSearch": "https://keeta.com/search?q=Cocina+La+Cantina"}'),
  ('casa_twist', 'كازا تويست', 'Casa Twist', ARRAY['mexican'], false, ARRAY['al_mohammadiyyah'], 'both', ARRAY['dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 18, 'trend', '$$', 'تاكو لحم بصوص البيت 🌮', 'Beef Tacos with House Sauce 🌮', ARRAY['تاكو ليلي', 'جلسات شباب', 'سريع ولذيذ'], ARRAY['Late-Night Tacos', 'Group Hangout', 'Quick & Tasty'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Casa+Twist+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Casa+Twist", "jahezSearch": "https://jahez.net/search?q=Casa+Twist", "keetaSearch": "https://keeta.com/search?q=Casa+Twist"}'),
  ('takosan', 'تاكوسان', 'Takosan', ARRAY['mexican', 'asian'], false, ARRAY['al_rawdah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 20, 'trend', '$$', 'تاكو جمبري مقلي بصوص الأفوكادو 🌮', 'Fried Shrimp Taco with Avo-Crema 🌮', ARRAY['تاكو آسيوي', 'ترند', 'نكهة مبتكرة'], ARRAY['Asian Fusion Taco', 'Trendy', 'Creative Flavor'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Takosan+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Takosan", "jahezSearch": "https://jahez.net/search?q=Takosan", "keetaSearch": "https://keeta.com/search?q=Takosan"}'),

  -- Sandwiches & Deli
  ('dank_sandwich', 'دانك ساندويتش', 'Dank Sandwich', ARRAY['sandwiches', 'burger'], false, ARRAY['al_zahra', 'al_rawdah', 'al_shati', 'abhur_al_shamaliyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 20, 'staple', '$$', 'ساندويتش بريسكيت مدخن 🥪', 'Smoked Brisket Sandwich 🥪', ARRAY['ساندويتشات ثقيلة', 'يشبع', 'سهرات شباب'], ARRAY['Loaded Sandwiches', 'Filling', 'Late-Night Groups'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Dank+Sandwich+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Dank+Sandwich", "jahezSearch": "https://jahez.net/search?q=Dank+Sandwich", "keetaSearch": "https://keeta.com/search?q=Dank+Sandwich"}'),
  ('sans_sandwich_bar', 'سانز ساندويتش بار', 'SANS Sandwich Bar', ARRAY['sandwiches', 'breakfast'], false, ARRAY['al_zahra'], 'both', ARRAY['breakfast', 'lunch'], 'يقفل 3:30 م', false, false, 18, 'trend', '$$', 'ساندويتش بيض وبسطرمة 🥪', 'Egg & Pastrami Sandwich 🥪', ARRAY['ساندويتش صباحي', 'برانش', 'قعدة خفيفة'], ARRAY['Morning Sandwich', 'Brunch', 'Casual Bite'], 4.6, '{"hungerstation": true, "jahez": false, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=SANS+Sandwich+Bar+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=SANS+Sandwich+Bar", "jahezSearch": "https://jahez.net/search?q=SANS+Sandwich+Bar", "keetaSearch": "https://keeta.com/search?q=SANS+Sandwich+Bar"}'),
  ('noho_deli', 'نوهو ديلي', 'Noho Deli', ARRAY['sandwiches'], false, ARRAY['al_shati'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 20, 'trend', '$$', 'ساندويتش بسطرمة نيويورك 🥪', 'New York Pastrami Sandwich 🥪', ARRAY['ديلي أمريكي', 'ساندويتش محترم', 'عشا متأخر'], ARRAY['American Deli', 'Serious Sandwich', 'Late Dinner'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Noho+Deli+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Noho+Deli", "jahezSearch": "https://jahez.net/search?q=Noho+Deli", "keetaSearch": "https://keeta.com/search?q=Noho+Deli"}'),
  ('shurekie', 'شريك', 'Shurekie', ARRAY['sandwiches'], false, ARRAY['al_rawdah'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 12:00 ص', false, false, 18, 'trend', '$', 'ساندويتش دجاج بصوص شريك 🥪', 'Chicken Sandwich with Shurekie Sauce 🥪', ARRAY['خفيف وسريع', 'ساندويتشات', 'قعدة كاجوال'], ARRAY['Light & Quick', 'Sandwich Spot', 'Casual Hangout'], 4.3, '{"hungerstation": true, "jahez": false, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shurekie+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shurekie", "jahezSearch": "https://jahez.net/search?q=Shurekie", "keetaSearch": "https://keeta.com/search?q=Shurekie"}'),
  ('chicago_sandwich', 'شيكاغو ساندوتش', 'Chicago Sandwich', ARRAY['sandwiches', 'burger'], false, ARRAY['al_salamah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 3:00 ص', true, false, 18, 'staple', '$$', 'ساندويتش ستيك فيلي بالجبنة الذائبة 🥩', 'Philly Cheesesteak Sandwich 🥩', ARRAY['فيلي ستيك', 'سريع ومشبع', 'سهرات'], ARRAY['Cheesesteak', 'Filling & Fast', 'Late Night'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Chicago+Sandwich+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Chicago+Sandwich", "jahezSearch": "https://jahez.net/search?q=Chicago+Sandwich", "keetaSearch": "https://keeta.com/search?q=Chicago+Sandwich"}'),

  -- Fatayer & Manakish
  ('shaikh_manqoosh', 'شيخ منقوش', 'Shaikh Manqoosh', ARRAY['fatayer'], false, ARRAY['al_rawdah'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 12:00 ص', false, false, 15, 'staple', '$', 'منقوشة جبنة وعكاوي 🫓', 'Akkawi Cheese Manousheh 🫓', ARRAY['خبز طازج', 'فطور سريع', 'منقوشة مزبوطة'], ARRAY['Fresh Bread', 'Quick Breakfast', 'Proper Manousheh'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shaikh+Manqoosh+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shaikh+Manqoosh", "jahezSearch": "https://jahez.net/search?q=Shaikh+Manqoosh", "keetaSearch": "https://keeta.com/search?q=Shaikh+Manqoosh"}'),
  ('forno_bakery', 'فورنو بيكري', 'Forno Bakery', ARRAY['fatayer'], false, ARRAY['al_salamah'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 11:30 م', false, false, 15, 'staple', '$', 'فطيرة جبنة وزعتر 🧀', 'Cheese & Zaatar Fatayer 🧀', ARRAY['فرن الصباح', 'خفيف ولذيذ', 'خبز طازج'], ARRAY['Morning Bakery', 'Light & Tasty', 'Fresh Bread'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Forno+Bakery+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Forno+Bakery", "jahezSearch": "https://jahez.net/search?q=Forno+Bakery", "keetaSearch": "https://keeta.com/search?q=Forno+Bakery"}'),
  ('fatayer_al_tayar', 'فطاير على الطاير', 'Fatayer Al Tayar', ARRAY['fatayer'], false, ARRAY['al_marwah'], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 4:00 ص', true, false, 18, 'staple', '$', 'فطيرة جبنة سائلة بالعسل 🫓', 'Creamy Cheese Fatayer with Honey 🫓', ARRAY['يفك أزمة', 'سهرات', 'فطاير حارة'], ARRAY['Late-Night Fix', 'Night Eats', 'Hot Fatayer'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Fatayer+Al+Tayar+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Fatayer+Al+Tayar", "jahezSearch": "https://jahez.net/search?q=Fatayer+Al+Tayar", "keetaSearch": "https://keeta.com/search?q=Fatayer+Al+Tayar"}'),
  ('shobak_chain', 'شوبك سلسلة', 'Shobak Chain', ARRAY['fatayer'], true, ARRAY[]::text[], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 18, 'staple', '$$', 'منقوشة حلوم بيستو 🫓', 'Halloumi Pesto Manousheh 🫓', ARRAY['فطور مضمون', 'مناقيش', 'سريع وعملي'], ARRAY['Reliable Breakfast', 'Manakeesh', 'Quick & Easy'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Shobak+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Shobak", "jahezSearch": "https://jahez.net/search?q=Shobak", "keetaSearch": "https://keeta.com/search?q=Shobak"}'),
  ('manousheh', 'منقوشة', 'Manoosheh', ARRAY['fatayer'], false, ARRAY['al_zahra', 'al_rawdah'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 1:00 ص', false, false, 15, 'trend', '$$', 'منقوشة لحمة بعجين مع جبنة 🫓', 'Meat with Dough & Cheese Manousheh 🫓', ARRAY['مناقيش لبنانية', 'عجينة رقيقة', 'فطور مرتب'], ARRAY['Lebanese Manakeesh', 'Thin Crust', 'Quality Breakfast'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Manoosheh+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Manoosheh", "jahezSearch": "https://jahez.net/search?q=Manoosheh", "keetaSearch": "https://keeta.com/search?q=Manoosheh"}'),

  -- Street Folk / Falafel
  ('abu_zaid_folk', 'أبو زيد شعبيات', 'Abu Zaid Folk', ARRAY['street_folk'], true, ARRAY[]::text[], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 18, 'staple', '$', 'مطبق مالح مع معصوب ملكي 🍌', 'Savory Mutabbaq with Royal Masoub 🍌', ARRAY['أسطورة جدة', 'شعبيات', 'سهرات'], ARRAY['Jeddah Icon', 'Folk Food', 'Late Night'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Abu+Zaid+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Abu+Zaid", "jahezSearch": "https://jahez.net/search?q=Abu+Zaid", "keetaSearch": "https://keeta.com/search?q=Abu+Zaid"}'),
  ('al_qarmoushi', 'القرموشي', 'Al Qarmoushi', ARRAY['street_folk'], true, ARRAY[]::text[], 'both', ARRAY['breakfast', 'dinner'], 'يقفل 12:30 ص', false, false, 15, 'staple', '$', 'فول قلابة مع تميس 🍲', 'Qalaba Foul with Tamees 🍲', ARRAY['فطور شعبي', 'جداوي قديم', 'سريع'], ARRAY['Folk Breakfast', 'Old Jeddah', 'Quick Bite'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Al+Qarmoushi+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Al+Qarmoushi", "jahezSearch": "https://jahez.net/search?q=Al+Qarmoushi", "keetaSearch": "https://keeta.com/search?q=Al+Qarmoushi"}'),
  ('foul_al_ghamdan', 'فول الغامدان', 'Foul Al-Ghamdan', ARRAY['street_folk'], false, ARRAY['al_marwah'], 'both', ARRAY['breakfast', 'dinner', 'late_night'], 'يقفل 1:30 ص', true, false, 15, 'staple', '$', 'فول مخصوص مع تميس حار 🫘', 'Special Foul with Hot Tamees 🫘', ARRAY['فول وتميس', 'شعبي مرتب', 'بعد السهرة'], ARRAY['Foul & Tamees', 'Proper Folk Food', 'After-Hours Bite'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Foul+Al+Ghamdan+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Foul+Al+Ghamdan", "jahezSearch": "https://jahez.net/search?q=Foul+Al+Ghamdan", "keetaSearch": "https://keeta.com/search?q=Foul+Al+Ghamdan"}'),
  ('operation_falafel', 'أوبريشن فلافل', 'Operation Falafel', ARRAY['street_folk'], false, ARRAY['al_rawdah', 'al_mohammadiyyah', 'al_naeem', 'al_faiha'], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 18, 'trend', '$', 'راب فلافل مع حمص وطرطور 🧆', 'Falafel Wrap with Hummus & Tarator 🧆', ARRAY['شعبي مودرن', 'لمّة أصحاب', 'فلافل مقرمشة'], ARRAY['Modern Street Food', 'Friends Gathering', 'Crispy Falafel'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Operation+Falafel+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Operation+Falafel", "jahezSearch": "https://jahez.net/search?q=Operation+Falafel", "keetaSearch": "https://keeta.com/search?q=Operation+Falafel"}'),
  ('falafel_thimar', 'فلافل ثمار', 'Falafel Thimar', ARRAY['street_folk'], false, ARRAY['al_salamah', 'al_naeem', 'al_zahra'], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 15, 'staple', '$', 'صحن فلافل ثمار مشكل مع شطة وفطيرة 🧆', 'Thimar Mixed Falafel Plate with Chili 🧆', ARRAY['فلافل محشية', 'سريع ومضمون', 'فطور وعشا'], ARRAY['Stuffed Falafel', 'Quick & Reliable', 'All-Day Bite'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Falafel+Thimar+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Falafel+Thimar", "jahezSearch": "https://jahez.net/search?q=Falafel+Thimar", "keetaSearch": "https://keeta.com/search?q=Falafel+Thimar"}'),

  -- Breakfast / Brunch
  ('brioche', 'بريوشيه', 'Brioché', ARRAY['breakfast', 'burger'], false, ARRAY['al_rawdah', 'al_salamah'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 12:00 ص', false, false, 20, 'trend', '$$$', 'فرنش توست كراميل مملح 🍞', 'Salted Caramel French Toast 🍞', ARRAY['فطور راقي', 'بريوش طازج', 'أجواء مميزة'], ARRAY['Gourmet Breakfast', 'Fresh Brioche', 'Signature Vibe'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Brioche+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Brioche", "jahezSearch": "https://jahez.net/search?q=Brioche", "keetaSearch": "https://keeta.com/search?q=Brioche"}'),
  ('early_club', 'إيرلي كلوب', 'Early Club', ARRAY['breakfast'], false, ARRAY['al_rawdah'], 'both', ARRAY['breakfast', 'lunch'], 'يقفل 4:30 م', false, false, 20, 'trend', '$$', 'بيض بنديكت بالدجاج المكسيكي 🍳', 'Mexican Chicken Eggs Benedict 🍳', ARRAY['برانش ترند', 'صباح رايق', 'قعدة أصحاب'], ARRAY['Trendy Brunch', 'Relaxed Morning', 'Friends Gathering'], 4.6, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Early+Club+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Early+Club", "jahezSearch": "https://jahez.net/search?q=Early+Club", "keetaSearch": "https://keeta.com/search?q=Early+Club"}'),
  ('lazy_cat', 'ليزي كات', 'Lazy Cat', ARRAY['breakfast'], false, ARRAY['al_rawdah'], 'both', ARRAY['breakfast', 'lunch'], 'يقفل 4:00 م', false, false, 20, 'trend', '$$', 'بانكيك ريكوتا بالعسل 🥞', 'Ricotta Pancakes with Honey 🥞', ARRAY['برانش كويتي', 'بانكيك مشهور', 'أجواء حلوة'], ARRAY['Kuwaiti Brunch', 'Famous Pancakes', 'Feel-Good Vibe'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Lazy+Cat+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Lazy+Cat", "jahezSearch": "https://jahez.net/search?q=Lazy+Cat", "keetaSearch": "https://keeta.com/search?q=Lazy+Cat"}'),

  -- Dessert & Cafes
  ('overdose', 'أوفر دوز', 'Overdose', ARRAY['dessert'], false, ARRAY['al_shati', 'al_rawdah', 'al_zahra'], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], '24 ساعة', true, true, 15, 'trend', '$$', 'كيكة الحليب بالزعفران 🍰', 'Saffron Milk Cake 🍰', ARRAY['حلى وقهوة', 'جلسات بحر', 'سهرات قهوة'], ARRAY['Dessert & Coffee', 'Seaside Seating', 'Late Coffee'], 4.3, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Overdose+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Overdose", "jahezSearch": "https://jahez.net/search?q=Overdose", "keetaSearch": "https://keeta.com/search?q=Overdose"}'),
  ('barns_chain', 'بارنز سلسلة', 'Barn''s Chain', ARRAY['dessert'], true, ARRAY[]::text[], 'both', ARRAY['breakfast', 'lunch', 'dinner', 'late_night'], '24 ساعة', true, true, 15, 'staple', '$', 'كرواسون مع لاتيه بارنز 🥐', 'Croissant with Barn''s Latte 🥐', ARRAY['قهوة سريعة', 'كلاسيك جدة', 'على الطريق'], ARRAY['Quick Coffee', 'Jeddah Classic', 'On the Go'], 4.4, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Barns+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Barns", "jahezSearch": "https://jahez.net/search?q=Barns", "keetaSearch": "https://keeta.com/search?q=Barns"}'),
  ('three_brews', 'ثري بروز', '3Brews', ARRAY['dessert'], false, ARRAY['al_faiha', 'al_zahra'], 'both', ARRAY['breakfast', 'lunch', 'dinner'], 'يقفل 12:30 ص', false, false, 15, 'trend', '$$', 'مولتن كيك شوكولاتة 🍫', 'Chocolate Molten Cake 🍫', ARRAY['حلى ترند', 'قهوة مختصة', 'جلسة رايقة'], ARRAY['Trendy Dessert', 'Specialty Coffee', 'Cozy Seating'], 4.7, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=3Brews+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=3Brews", "jahezSearch": "https://jahez.net/search?q=3Brews", "keetaSearch": "https://keeta.com/search?q=3Brews"}'),

  -- Seafood
  ('twina_seafood', 'توينا', 'Twina Seafood', ARRAY['seafood'], false, ARRAY['al_mohammadiyyah', 'al_hamra', 'al_zahra', 'al_shati', 'abhur_al_shamaliyah'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 2:00 ص', true, false, 25, 'staple', '$$$', 'سمك ناجل مشوي مع رز صيادية 🐟', 'Grilled Najil with Sayadiyah Rice 🐟', ARRAY['سمك طازج', 'عزايم بحرية', 'جداوي أصيل'], ARRAY['Fresh Seafood', 'Seafood Feasts', 'Jeddah Classic'], 4.5, '{"hungerstation": true, "jahez": true, "keeta": false}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Twina+Seafood+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Twina+Seafood", "jahezSearch": "https://jahez.net/search?q=Twina+Seafood", "keetaSearch": "https://keeta.com/search?q=Twina+Seafood"}'),
  ('asmak_tharaa', 'أسماك ثراء', 'Asmak Tharaa', ARRAY['seafood'], false, ARRAY['al_naeem', 'al_zahra'], 'both', ARRAY['lunch', 'dinner', 'late_night'], 'يقفل 1:30 ص', true, false, 25, 'staple', '$$', 'صحن ثراء البحري المشكل 🦐', 'Tharaa Mixed Seafood Platter 🦐', ARRAY['سمك طازج', 'صيادية', 'عائلي'], ARRAY['Fresh Seafood', 'Sayadiyah', 'Family Friendly'], 4.2, '{"hungerstation": true, "jahez": true, "keeta": true}', '{"googleMaps": "https://www.google.com/maps/search/?api=1&query=Asmak+Tharaa+Jeddah", "hungerstationSearch": "https://hungerstation.com/sa-ar/search?q=Asmak+Tharaa", "jahezSearch": "https://jahez.net/search?q=Asmak+Tharaa", "keetaSearch": "https://keeta.com/search?q=Asmak+Tharaa"}')
ON CONFLICT (id) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  is_city_wide = EXCLUDED.is_city_wide,
  branches = EXCLUDED.branches,
  dining_mode = EXCLUDED.dining_mode,
  time_slots = EXCLUDED.time_slots,
  closing_time_ar = EXCLUDED.closing_time_ar,
  is_open_late = EXCLUDED.is_open_late,
  is_24_hours = EXCLUDED.is_24_hours,
  avg_prep_minutes = EXCLUDED.avg_prep_minutes,
  tier = EXCLUDED.tier,
  price_tier = EXCLUDED.price_tier,
  signature_dish_ar = EXCLUDED.signature_dish_ar,
  signature_dish_en = EXCLUDED.signature_dish_en,
  vibe_tags_ar = EXCLUDED.vibe_tags_ar,
  vibe_tags_en = EXCLUDED.vibe_tags_en,
  rating = EXCLUDED.rating,
  platforms = EXCLUDED.platforms,
  links = EXCLUDED.links;

